
# Docker compose file to set up 

# - ngix-manager
# - guacamole 
#  and portainer to manage all

version: '3.1'

services:
# username=guacadmin, pass=guacadmin
  guacamole:
      image: oznu/guacamole
      container_name: guacamole
      volumes:
        - ./config:/config
      ports:
        - 8080:8080
  nginx-manager:
      image: 'jc21/nginx-proxy-manager:latest'
      restart: unless-stopped
      ports:
        - '80:80'
        - '81:81'
        - '443:443'
      volumes:
        - ./data:/data
        - ./letsencrypt:/etc/letsencrypt
  portainer:
      image: portainer/portainer-ce:latest
      container_name: portainer
      restart: unless-stopped
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./portainer-data:/data
      ports:
        - 9000:9000
  wordpress:
      image: wordpress
      restart: always
      ports:
        - 8080:80
      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: exampleuser
        WORDPRESS_DB_PASSWORD: examplepass
        WORDPRESS_DB_NAME: exampledb
      volumes:
        - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: